### PR TITLE
Icon cleanup and re-vector

### PR DESCRIPTION
**Pull request by IndulgentHuman**
Icons in the controller, events and explore folders were cleaned up by removing excess points or recreated with reference from available sources that Bungie has put out.

### CODE REVIEW

**Comment by justrealmilk** [comment]
i appreciate the work you've done but i do have some issues

- controller icons are extracted from the game content and i'd prefer to match the canonical
- the changes that follow are hard to track as i'd need to check each changed file 
- and i'm hesitant to marge anything unless i'm 100% sure it's perfect as other repos depend on this 

i might see if i can convince someone else to take up the reigns 

brb

**Comment by IndulgentHuman** [comment]
No worries, totally understand.

**Comment by inexorableAce** [comment]
ok looked through all of these, most seem fine with the exception of:

image


Let's start by reverting the controller icon changes from the PR and fixing cosmodrome, then I'll dig into what's left. Also not sure about the git.ignore add @justrealmilk can weigh in on that.

**Comment by IndulgentHuman** [comment]
Got it Thanks Ace, ah I'll fix that cosmodrome one in the AM. gitignore was just so git wouldn't commit the .DS-Store hidden files that macOS creates

**Pull request closed without merging**
